ALTER TABLE editoras
ADD COLUMN uf VARCHAR(255) NOT NULL,
ADD COLUMN bairro VARCHAR(255) NOT NULL,
ADD COLUMN cidade VARCHAR(255) NOT NULL,
ADD COLUMN rua VARCHAR(255) NOT NULL,
ADD COLUMN numero VARCHAR(255) NOT NULL,
ADD COLUMN complemento VARCHAR(255);